const Products = {
  pacificSchool: {
    buzoCompleto: [
      {
        name: "Buzo completo",
        price: 22500,
        description: "Buzo completo de algodón",
        image: "images/buzo.jpg",
        stock: 10,
        size: "4",
      },
      {
        name: "Buzo completo",
        price: 23000,
        description: "Buzo completo de algodón",
        image: "images/buzo.jpg",
        stock: 15,
        size: "6",
      },
      {
        name: "Buzo completo",
        price: 23500,
        description: "Buzo completo de algodón",
        image: "images/buzo.jpg",
        stock: 20,
        size: "8",
      },
      {
        name: "Buzo completo",
        price: 24000,
        description: "Buzo completo de algodón",
        image: "images/buzo.jpg",
        stock: 12,
        size: "10",
      },
      {
        name: "Buzo completo",
        price: 26000,
        description: "Buzo completo de algodón",
        image: "images/buzo.jpg",
        stock: 18,
        size: "12",
      },
      {
        name: "Buzo completo",
        price: 27000,
        description: "Buzo completo de algodón",
        image: "images/buzo.jpg",
        stock: 10,
        size: "14",
      },
      {
        name: "Buzo completo",
        price: 28000,
        description: "Buzo completo de algodón",
        image: "images/buzo.jpg",
        stock: 10,
        size: "16",
      },
      {
        name: "Buzo completo",
        price: 32000,
        description: "Buzo completo de algodón",
        image: "images/buzo.jpg",
        stock: 10,
        size: "S",
      },
      {
        name: "Buzo completo",
        price: 35000,
        description: "Buzo completo de algodón",
        image: "images/buzo.jpg",
        stock: 8,
        size: "M",
      },
      {
        name: "Buzo completo",
        price: 36000,
        description: "Buzo completo de algodón",
        image: "images/buzo.jpg",
        stock: 5,
        size: "L",
      },
      {
        name: "Buzo completo",
        price: 37000,
        description: "Buzo completo de algodón",
        image: "images/buzo.jpg",
        stock: 3,
        size: "XL",
      },
    ],
    delantales: {
      hombre: [
        {
          name: "Delantal",
          price: 12000,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_hombre.jpg",
          stock: 10,
          size: "4",
        },
        {
          name: "Delantal",
          price: 12500,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_hombre.jpg",
          stock: 12,
          size: "6",
        },
        {
          name: "Delantal",
          price: 13000,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_hombre.jpg",
          stock: 15,
          size: "8",
        },
        {
          name: "Delantal",
          price: 13500,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_hombre.jpg",
          stock: 18,
          size: "10",
        },
        {
          name: "Delantal",
          price: 14000,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_hombre.jpg",
          stock: 20,
          size: "12",
        },
        {
          name: "Delantal",
          price: 14500,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_hombre.jpg",
          stock: 15,
          size: "14",
        },
        {
          name: "Delantal",
          price: 15000,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_hombre.jpg",
          stock: 15,
          size: "16",
        },
        {
          name: "Delantal",
          price: 15500,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_hombre.jpg",
          stock: 15,
          size: "S",
        },
        {
          name: "Delantal",
          price: 16000,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_hombre.jpg",
          stock: 12,
          size: "M",
        },
        {
          name: "Delantal",
          price: 16500,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_hombre.jpg",
          stock: 10,
          size: "L",
        },
        {
          name: "Delantal",
          price: 17000,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_hombre.jpg",
          stock: 8,
          size: "XL",
        },
      ],
      mujer: [
        {
          name: "Delantal",
          price: 12000,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_mujer.jpg",
          stock: 10,
          size: "4",
        },
        {
          name: "Delantal",
          price: 12500,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_mujer.jpg",
          stock: 12,
          size: "6",
        },
        {
          name: "Delantal",
          price: 13000,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_mujer.jpg",
          stock: 15,
          size: "8",
        },
        {
          name: "Delantal",
          price: 13500,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_mujer.jpg",
          stock: 18,
          size: "10",
        },
        {
          name: "Delantal",
          price: 14000,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_mujer.jpg",
          stock: 20,
          size: "12",
        },
        {
          name: "Delantal",
          price: 14500,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_mujer.jpg",
          stock: 15,
          size: "14",
        },
        {
          name: "Delantal",
          price: 15000,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_mujer.jpg",
          stock: 15,
          size: "16",
        },
        {
          name: "Delantal",
          price: 15500,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_mujer.jpg",
          stock: 15,
          size: "S",
        },
        {
          name: "Delantal",
          price: 16000,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_mujer.jpg",
          stock: 12,
          size: "M",
        },
        {
          name: "Delantal",
          price: 16500,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_mujer.jpg",
          stock: 10,
          size: "L",
        },
        {
          name: "Delantal",
          price: 17000,
          description: "Delantal colegio the pacific school",
          image: "images/delantal_mujer.jpg",
          stock: 8,
          size: "XL",
        },
      ],
      kinder: [
        {
          name: "Delantal",
          price: 12500,
          description: "Delantal kinder",
          image: "images/delantal_kinder.jpg",
          stock: 10,
          size: "4",
        },
        {
          name: "Delantal",
          price: 12500,
          description: "Delantal kinder",
          image: "images/delantal_kinder.jpg",
          stock: 10,
          size: "6",
        },
        {
          name: "Delantal",
          price: 12500,
          description: "Delantal kinder",
          image: "images/delantal_kinder.jpg",
          stock: 10,
          size: "8",
        },
      ],
    },
    faldas: [
      {
        name: "Falda",
        price: 18000,
        description: "Falda colegio the pacific school",
        image: "images/falda.jpg",
        stock: 18,
        size: "10",
      },
      {
        name: "Falda",
        price: 18500,
        description: "Falda colegio the pacific school",
        image: "images/falda.jpg",
        stock: 20,
        size: "12",
      },
      {
        name: "Falda",
        price: 19500,
        description: "Falda colegio the pacific school",
        image: "images/falda.jpg",
        stock: 15,
        size: "14",
      },
      {
        name: "Falda",
        price: 20000,
        description: "Falda colegio the pacific school",
        image: "images/falda.jpg",
        stock: 10,
        size: "16",
      },
      {
        name: "Falda",
        price: 21000,
        description: "Falda colegio the pacific school",
        image: "images/falda.jpg",
        stock: 8,
        size: "S",
      },
      {
        name: "Falda",
        price: 22000,
        description: "Falda colegio the pacific school",
        image: "images/falda.jpg",
        stock: 12,
        size: "M",
      },
      {
        name: "Falda",
        price: 23000,
        description: "Falda colegio the pacific school",
        image: "images/falda.jpg",
        stock: 10,
        size: "L",
      },
      {
        name: "Falda",
        price: 24000,
        description: "Falda colegio the pacific school",
        image: "images/falda.jpg",
        stock: 8,
        size: "XL",
      },
    ],
    pantalonBuzo: [
      {
        name: "Pantalón buzo",
        price: 11000,
        description: "Pantalón buzo",
        image: "images/pantalon_buzo_hombre.jpg",
        stock: 10,
        size: "4",
      },
      {
        name: "Pantalón buzo",
        price: 11500,
        description: "Pantalón buzo",
        image: "images/pantalon_buzo_hombre.jpg",
        stock: 12,
        size: "6",
      },
      {
        name: "Pantalón buzo",
        price: 12000,
        description: "Pantalón buzo",
        image: "images/pantalon_buzo_hombre.jpg",
        stock: 15,
        size: "8",
      },
      {
        name: "Pantalón buzo",
        price: 12500,
        description: "Pantalón buzo",
        image: "images/pantalon_buzo_hombre.jpg",
        stock: 18,
        size: "10",
      },
      {
        name: "Pantalón buzo",
        price: 13000,
        description: "Pantalón buzo",
        image: "images/pantalon_buzo_hombre.jpg",
        stock: 20,
        size: "12",
      },
      {
        name: "Pantalón buzo",
        price: 13500,
        description: "Pantalón buzo",
        image: "images/pantalon_buzo_hombre.jpg",
        stock: 15,
        size: "14",
      },
      {
        name: "Pantalón buzo",
        price: 14000,
        description: "Pantalón buzo",
        image: "images/pantalon_buzo_hombre.jpg",
        stock: 10,
        size: "16",
      },
      {
        name: "Pantalón buzo",
        price: 16000,
        description: "Pantalón buzo",
        image: "images/pantalon_buzo_hombre.jpg",
        stock: 8,
        size: "S",
      },
      {
        name: "Pantalón buzo",
        price: 17000,
        description: "Pantalón buzo",
        image: "images/pantalon_buzo_hombre.jpg",
        stock: 12,
        size: "M",
      },
      {
        name: "Pantalón buzo",
        price: 18000,
        description: "Pantalón buzo",
        image: "images/pantalon_buzo_hombre.jpg",
        stock: 10,
        size: "L",
      },
      {
        name: "Pantalón buzo",
        price: 19000,
        description: "Pantalón buzo",
        image: "images/pantalon_buzo_hombre.jpg",
        stock: 8,
        size: "XL",
      },
    ],
    poleronBuzo: [
      {
        name: "Poleron buzo",
        price: 13000,
        description: "Poleron buzo",
        image: "images/poleron_buzo_hombre.jpg",
        stock: 10,
        size: "4",
      },
      {
        name: "Poleron buzo",
        price: 13500,
        description: "Poleron buzo",
        image: "images/poleron_buzo_hombre.jpg",
        stock: 12,
        size: "6",
      },
      {
        name: "Poleron buzo",
        price: 14000,
        description: "Poleron buzo",
        image: "images/poleron_buzo_hombre.jpg",
        stock: 15,
        size: "8",
      },
      {
        name: "Poleron buzo",
        price: 14500,
        description: "Poleron buzo",
        image: "images/poleron_buzo_hombre.jpg",
        stock: 18,
        size: "10",
      },
      {
        name: "Poleron buzo",
        price: 15000,
        description: "Poleron buzo",
        image: "images/poleron_buzo_hombre.jpg",
        stock: 20,
        size: "12",
      },
      {
        name: "Poleron buzo",
        price: 15500,
        description: "Poleron buzo",
        image: "images/poleron_buzo_hombre.jpg",
        stock: 15,
        size: "14",
      },
      {
        name: "Poleron buzo",
        price: 16000,
        description: "Poleron buzo",
        image: "images/poleron_buzo_hombre.jpg",
        stock: 10,
        size: "16",
      },
      {
        name: "Poleron buzo",
        price: 17500,
        description: "Poleron buzo",
        image: "images/poleron_buzo_hombre.jpg",
        stock: 8,
        size: "S",
      },
      {
        name: "Poleron buzo",
        price: 18000,
        description: "Poleron buzo",
        image: "images/poleron_buzo_hombre.jpg",
        stock: 12,
        size: "M",
      },
      {
        name: "Poleron buzo",
        price: 18500,
        description: "Poleron buzo",
        image: "images/poleron_buzo_hombre.jpg",
        stock: 10,
        size: "L",
      },
      {
        name: "Poleron buzo",
        price: 19000,
        description: "Poleron buzo",
        image: "images/poleron_buzo_hombre.jpg",
        stock: 8,
        size: "XL",
      },
    ],
    poleraPique: [
      {
        name: "Polera piqué",
        price: 8900,
        description: "Polera piqué",
        image: "images/polera_pique_ml_hombre.jpg",
        stock: 10,
        size: "4",
      },
      {
        name: "Polera piqué",
        price: 8900,
        description: "Polera piqué",
        image: "images/polera_pique_ml_hombre.jpg",
        stock: 12,
        size: "6",
      },
      {
        name: "Polera piqué",
        price: 9900,
        description: "Polera piqué",
        image: "images/polera_pique_ml_hombre.jpg",
        stock: 15,
        size: "8",
      },
      {
        name: "Polera piqué",
        price: 9900,
        description: "Polera piqué",
        image: "images/polera_pique_ml_hombre.jpg",
        stock: 18,
        size: "10",
      },
      {
        name: "Polera piqué",
        price: 10900,
        description: "Polera piqué",
        image: "images/polera_pique_ml_hombre.jpg",
        stock: 20,
        size: "12",
      },
      {
        name: "Polera piqué",
        price: 10900,
        description: "Polera piqué",
        image: "images/polera_pique_ml_hombre.jpg",
        stock: 15,
        size: "14",
      },
      {
        name: "Polera piqué",
        price: 11900,
        description: "Polera piqué",
        image: "images/polera_pique_ml_hombre.jpg",
        stock: 10,
        size: "16",
      },
      {
        name: "Polera piqué",
        price: 11900,
        description: "Polera piqué",
        image: "images/polera_pique_ml_hombre.jpg",
        stock: 8,
        size: "S",
      },
      {
        name: "Polera piqué",
        price: 12900,
        description: "Polera piqué",
        image: "images/polera_pique_ml_hombre.jpg",
        stock: 12,
        size: "M",
      },
      {
        name: "Polera piqué",
        price: 12900,
        description: "Polera piqué",
        image: "images/polera_pique_ml_hombre.jpg",
        stock: 10,
        size: "L",
      },
      {
        name: "Polera piqué",
        price: 13900,
        description: "Polera piqué",
        image: "images/polera_pique_ml_hombre.jpg",
        stock: 8,
        size: "XL",
      },
    ],
    poleraPolo: [
      {
        name: "Polera polo",
        price: 7900,
        description: "Polera polo",
        image: "images/polera_pique_mc_hombre.jpg",
        stock: 10,
        size: "4",
      },
      {
        name: "Polera polo",
        price: 7900,
        description: "Polera polo",
        image: "images/polera_pique_mc_hombre.jpg",
        stock: 12,
        size: "6",
      },
      {
        name: "Polera polo",
        price: 8900,
        description: "Polera polo",
        image: "images/polera_pique_mc_hombre.jpg",
        stock: 15,
        size: "8",
      },
      {
        name: "Polera polo",
        price: 8900,
        description: "Polera polo",
        image: "images/polera_pique_mc_hombre.jpg",
        stock: 18,
        size: "10",
      },
      {
        name: "Polera polo",
        price: 9900,
        description: "Polera polo",
        image: "images/polera_pique_mc_hombre.jpg",
        stock: 20,
        size: "12",
      },
      {
        name: "Polera polo",
        price: 9900,
        description: "Polera polo",
        image: "images/polera_pique_mc_hombre.jpg",
        stock: 15,
        size: "14",
      },
      {
        name: "Polera polo",
        price: 10900,
        description: "Polera polo",
        image: "images/polera_pique_mc_hombre.jpg",
        stock: 10,
        size: "16",
      },
      {
        name: "Polera polo",
        price: 10900,
        description: "Polera polo",
        image: "images/polera_pique_mc_hombre.jpg",
        stock: 8,
        size: "S",
      },
      {
        name: "Polera polo",
        price: 11900,
        description: "Polera polo",
        image: "images/polera_pique_mc_hombre.jpg",
        stock: 12,
        size: "M",
      },
      {
        name: "Polera polo",
        price: 11900,
        description: "Polera polo",
        image: "images/polera_pique_mc_hombre.jpg",
        stock: 10,
        size: "L",
      },
      {
        name: "Polera polo",
        price: 12900,
        description: "Polera polo",
        image: "images/polera_pique_mc_hombre.jpg",
        stock: 8,
        size: "XL",
      },
    ],
    pantalonTela: [
      {
        name: "Pantalón tela",
        price: 20000,
        description: "Pantalón tela",
        image: "images/pantalon_tela.jpg",
        stock: 18,
        size: "10",
      },
      {
        name: "Pantalón tela",
        price: 21000,
        description: "Pantalón tela",
        image: "images/pantalon_tela.jpg",
        stock: 20,
        size: "12",
      },
      {
        name: "Pantalón tela",
        price: 22000,
        description: "Pantalón tela",
        image: "images/pantalon_tela.jpg",
        stock: 15,
        size: "14",
      },
      {
        name: "Pantalón tela",
        price: 23000,
        description: "Pantalón tela",
        image: "images/pantalon_tela.jpg",
        stock: 10,
        size: "16",
      },
      {
        name: "Pantalón tela",
        price: 24000,
        description: "Pantalón tela",
        image: "images/pantalon_tela.jpg",
        stock: 8,
        size: "S",
      },
      {
        name: "Pantalón tela",
        price: 25000,
        description: "Pantalón tela",
        image: "images/pantalon_tela.jpg",
        stock: 12,
        size: "M",
      },
      {
        name: "Pantalón tela",
        price: 26000,
        description: "Pantalón tela",
        image: "images/pantalon_tela.jpg",
        stock: 10,
        size: "L",
      },
      {
        name: "Pantalón tela",
        price: 27000,
        description: "Pantalón tela",
        image: "images/pantalon_tela.jpg",
        stock: 8,
        size: "XL",
      },
    ],
    polar: [
      {
        name: "Polar",
        price: 13500,
        description: "Polar de algodón",
        image: "images/buzo.jpg",
        stock: 15,
        size: "6",
      },
      {
        name: "Polar",
        price: 13500,
        description: "Polar de algodón",
        image: "images/buzo.jpg",
        stock: 20,
        size: "8",
      },
      {
        name: "Polar",
        price: 14500,
        description: "Polar de algodón",
        image: "images/buzo.jpg",
        stock: 12,
        size: "10",
      },
      {
        name: "Polar",
        price: 14500,
        description: "Polar de algodón",
        image: "images/buzo.jpg",
        stock: 18,
        size: "12",
      },
      {
        name: "Polar",
        price: 16500,
        description: "Polar de algodón",
        image: "images/buzo.jpg",
        stock: 10,
        size: "14",
      },
      {
        name: "Polar",
        price: 16500,
        description: "Polar de algodón",
        image: "images/buzo.jpg",
        stock: 10,
        size: "16",
      },
      {
        name: "Polar",
        price: 17500,
        description: "Polar de algodón",
        image: "images/buzo.jpg",
        stock: 10,
        size: "S",
      },
      {
        name: "Polar",
        price: 17500,
        description: "Polar de algodón",
        image: "images/buzo.jpg",
        stock: 8,
        size: "M",
      },
      {
        name: "Polar",
        price: 18500,
        description: "Polar de algodón",
        image: "images/buzo.jpg",
        stock: 5,
        size: "L",
      },
      {
        name: "Polar",
        price: 19500,
        description: "Polar de algodón",
        image: "images/buzo.jpg",
        stock: 3,
        size: "XL",
      },
    ],
  },
};

module.exports = { Products };
